name: Envoi Anniversaires Paheko

on:
  schedule:
    # Exécution tous les jours à 08h00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Permet de lancer le script manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v5

      - name: Installer Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: pip install requests

      - name: Exécuter le script
        env:
          PAHEKO_URL: ${{ secrets.PAHEKO_URL }}
          PAHEKO_USER: ${{ secrets.PAHEKO_USER }}
          PAHEKO_PASSWORD: ${{ secrets.PAHEKO_PASSWORD }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        run: python anniversaires.py
